### ISSUE TITLE
Unknown error (0x100001a8)

### ISSUE THREAD

**Issue by wz2b** [estradege/citect#10]
Hi,

I am trying to make a very small program to read tag values.  The program is very simple:

```
class TestClass
{
    static void Main(string[] args)
    {
        var wrapper = new Citect.CtApi(true);
        wrapper.Open();

        string t = wrapper.TagRead("ALARM_RESET_BIT");
        Console.WriteLine(t);

        wrapper.Close();
    }
}
```

On TagRead() I get this:
```
An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in AlarmClient.exe
Unknown error (0x100001a8)
```

I confirmed that the tag does exist and that PlantSCADA is running.  I also set up my csproj to specifically use .net 4.8:

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
```

There is no error on the .Open() call.  I traced through that call just to be sure and:

```
_ctapi = CtOpen(computer, user, password, 0);
```

is returning some kind of handle (not NULL) so I think the open succeeded.

Any idea what this Unknown error could be?

--C

**Comment by wz2b** [comment]
Just by way of a little more context, I tried something different:

```
class TestClass
{

    static void Main(string[] args)
    {
        var wrapper = new Citect.CtApi(true);
        wrapper.Open();

        Console.WriteLine("find some tags");
        var tags = wrapper.Find("Tag", "TAG=*SOFC_2*", "", "TAG");

        
        foreach(var onetag in tags)
        {
            foreach (var ot in onetag)
            {
                Console.WriteLine(ot.Key + ": " + ot.Value);
            }
        }

        Console.WriteLine("Get one tag");
        string t = wrapper.TagRead("SOFC_2_TEST_RUNNING");
        Console.WriteLine(t);

        wrapper.Close();
    }
}
```

The first part dumps all the tags that matched a tag pattern.  It works, and gives me a list like this:

```
TAG: SOFC_2_GAS_5_SV_MON
TAG: SOFC_2_GAS_6_SELECT_FROM_HMI
TAG: SOFC_2_GAS_6_SELECTED
TAG: SOFC_2_GAS_6_SV_MOF
TAG: SOFC_2_GAS_6_SV_MON
TAG: SOFC_2_TEST_RUNNING
```

so as you can see `SOFC_2_TEST_RUNNING` is a valid tag.  Tracing TagRead further:

```var result = CtTagRead(_ctapi, tag, value, value.Capacity);```

This returns false.

I also tried naming the tag I'm requesting CLUSTER.TAGNAME and CLUSTER.DEVICE.TAGNAME which also didn't work.

**Comment by estradege** [comment]
Hi,
the Unknown error (0x100001a8) refer to 424 error code (Tag Not Found). TagRead also raise Unknown error (0x1000000c) if tag has a bad quality but this behaviour is not describe in the citect help.
