### ISSUE TITLE
Unable to load DLL 'CtApi.dll'

### ISSUE THREAD

**Issue by wmmihaa** [estradege/citect#12]
Hi,
I'm a consultant trying to help my customer integrating with Citect. I have been given two sets of assemblies; CtApi.Win32.Redist and CtApi.x64.Redist.

I've installed all assemblies in the C:\ProgramData\CitectCtApi directory, but when I run the Console sample if fails with:
``` 
Unable to load DLL 'CtApi.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

I've tried both the x86 and 64 bits dll's.

Is there a specific version of the dll's I should ask for?

Cheers
Mikael

**Comment by estradege** [comment]
Hi Mikael,
Version 2.1.0 add SetCtApiDirectory function. Called it before Open should avoid dependencies issues.
* Check the [Citect.CtApi](https://github.com/estradege/citect/wiki/Citect.CtApi-Examples) examples
