### ISSUE TITLE
Could not load file or assembly 'Citect.Platform.Transport.Interfaces, Version=8.40.0.0

### ISSUE THREAD

**Issue by franksandersen** [estradege/citect#13]
I keep getting this error when launching my .net6 console program using nuget Citect.CtApi:
 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Citect.Platform.Transport.Interfaces, Version=8.40.0.0, Culture=neutral, PublicKeyToken=13aaee2494f61799' or one of its dependencies. 

On the server I have this file ...\Bin (x64)\Citect.Platform.Transport.Interfaces.dll in version 8.40.0.455

How can I address this specific version? I have tried different versions of the nuget package Citect.CtApi (from 1.5.0.0 to 2.0.0.0) but always same error...

**Comment by estradege** [comment]
Version 2.1.0 add SetCtApiDirectory function. Called it before Open should avoid dependencies issues.
* Check the [Citect.CtApi](https://github.com/estradege/citect/wiki/Citect.CtApi-Examples) examples
