### ISSUE TITLE
Alarm ODBC setup - System

### ISSUE THREAD

**Issue by simonmcconnell** [estradege/citect#3]
Hi,

When setting up the Alarm ODBC connection, the System dropdown is empty for me.  Did you find any docs on this or know what steps to take for that to be populated?

![image](https://user-images.githubusercontent.com/22566656/111051531-773bb400-849f-11eb-9eaa-b90070dda396.png)

**Comment by estradege** [comment]
Hi, as you can see in the wiki [Citect.AlarmDriver](https://github.com/estradege/citect/wiki/Citect.AlarmDriver-Examples), both AlarmDbConnection and AlarmDbService does not need to configure an ODBC connection.
