### ISSUE TITLE
Consider extending Open to include nMode arguments

### ISSUE THREAD

**Issue by hexagonhill** [estradege/citect#5]
Due to running a  windows service there was a need to pass 
CT_OPEN_BATCH - Disables the display of message boxes when an error occurs. 
to ctOpen

Eg.
`   public enum CT_OPEN
    {
        NONE = 0,
        CRYPT = 1,
        RECONNECT = 2,
        READ_ONLY = 4,
        BATCH = 8
    }
`
`public void Open(string computer, string user, string password, CT_OPEN flags = CT_OPEN.NONE)`

Without CT_OPEN_BATCH  the service would lockup.
If you want I can submit a PR but the Citect.CtApi.csproj has an absolute path that was removed and not sure how that affects your build.

Thanks

**Comment by estradege** [comment]
Version 2.1.0 add the ability to set the open mode.
Regards,
