### ISSUE TITLE
Cannot find .DLL files

### ISSUE THREAD

**Issue by ghost** [estradege/citect#9]
For some reason when running the windows forms app with latest version of Aveva Plant SCADA redistributables. When attempting the login button an error returns that the DLL cannot be imported even when placed in location referenced in DLL import location.

**Comment by estradege** [comment]
Hi Climberbee,
try to put the citect dlls in the C:\ProgramData\CitectCtApi folder. Don't forget to put this path to the "system path" environment variable.

**Comment by estradege** [comment]
Version 2.1.0 add SetCtApiDirectory function. Called it before Open should avoid dependencies issues.
* Check the [Citect.CtApi](https://github.com/estradege/citect/wiki/Citect.CtApi-Examples) examples
